# Assignment 0

### <span style="color:chocolate"> Submission requirements </span>

Your work will not be graded if your notebook doesn't include output. In other words, <span style="color:red"> make sure to rerun your notebook before submitting to Gradescope </span> (Note: if you are using Google Colab: go to Edit > Notebook Settings  and uncheck Omit code cell output when saving this notebook, otherwise the output is not printed).

Additional points may be deducted if these requirements are not met:

    
* Comment your code;
* Each graph should have a title, labels for each axis, and (if needed) a legend. Each graph should be understandable on its own;
* Try and minimize the use of the global namespace (meaning, keep things inside functions).
---

### Import libraries

In [3]:
import numpy as np
np.random.seed(seed=1)

---
### <span style="color:chocolate">Exercise 1:</span> Homogenous data types (10 points)

1. Create a numpy array (my_array1) containing only integer values. Print the shape of the array and the type of its elements;
2. Create another numpy array (my_array2) containing a mix of integer and string values. Print the shape of the array and the type of its elements. Comment on the type of its elements.

In [10]:
# YOUR CODE HERE
my_array1 = np.random.randint(0, 10, size=5)
print(my_array1)
print("Shape of my_array1:", my_array1.shape)
print("Data type of my_array1 elements:", my_array1.dtype)

my_array2 = np.array([1, "two", 3, "four", 5])
print("Shape of my_array2:", my_array2.shape)
print("Data type of my_array2 elements:", my_array2.dtype)

[2 4 5 2 4]
Shape of my_array1: (5,)
Data type of my_array1 elements: int32
Shape of my_array2: (5,)
Data type of my_array2 elements: <U21


---
#### <span style="color:chocolate">Exercise 2:</span> The size attribute (10 points)

Create a numpy array (my_array3) and print its shape, size, and data type. What does size represent?

In [3]:
# YOUR CODE HERE
my_array3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Shape:", my_array3.shape)
print("Size:", my_array3.size)
print("Data type:", my_array3.dtype)

# Size: The total number of elements in the array (9 in this case, as it's a 3x3 array).

Shape: (3, 3)
Size: 9
Data type: int64


---
#### <span style="color:chocolate">Exercise 3:</span> Tabular data layout (10 points)

Create a tabular data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:
* the first input is num_samples, and
* the second input is num_features. 

Print the shape of the array.

In [11]:
# already defined first and second inputs
num_samples = 100
num_features = 17

# YOUR CODE HERE
data_array = np.random.random((num_samples, num_features))

print(data_array)
print("Shape of the array:", data_array.shape)

[[0.20445225 0.87811744 0.02738759 ... 0.08504421 0.03905478 0.16983042]
 [0.8781425  0.09834683 0.42110763 ... 0.78927933 0.10322601 0.44789353]
 [0.9085955  0.29361415 0.28777534 ... 0.10233443 0.41405599 0.69440016]
 ...
 [0.37114718 0.29482088 0.91176317 ... 0.74238343 0.3902647  0.7598254 ]
 [0.9029359  0.58742002 0.09040972 ... 0.04345154 0.94857277 0.31129608]
 [0.79897284 0.8106291  0.85999859 ... 0.32683068 0.24946221 0.21926791]]
Shape of the array: (100, 17)


---
#### <span style="color:chocolate">Exercise 4:</span> Image data layout (10 points)

Create an image data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:

* the first input is num_images;
* the second input is num_rows;
* the third input is num_cols;
* the fourth input is num_channels.

Print the shape of the array.

In [12]:
# already defined inputs
num_images = 100
num_rows = 256
num_cols = 256
num_channels = 3 #(RGB)

# YOUR CODE HERE
image_data_array = np.random.random((num_images, num_rows, num_cols, num_channels))

print(image_data_array)
print("Shape of the array:", image_data_array.shape)


[[[[0.79966084 0.50239501 0.08318989]
   [0.77698419 0.53364908 0.73938779]
   [0.51539369 0.39994592 0.98624678]
   ...
   [0.69914657 0.39498706 0.79749598]
   [0.78641708 0.15552858 0.31781755]
   [0.34398318 0.3641703  0.56664556]]

  [[0.04168744 0.65996972 0.20163176]
   [0.41646256 0.45089266 0.34872677]
   [0.38328031 0.18030606 0.06813006]
   ...
   [0.19596701 0.15675161 0.75451701]
   [0.32997323 0.64419569 0.5654556 ]
   [0.89953092 0.88068362 0.4431114 ]]

  [[0.20473509 0.63219238 0.63683598]
   [0.6924175  0.9074732  0.78258098]
   [0.62529094 0.6009656  0.21275904]
   ...
   [0.84635588 0.4842779  0.45106879]
   [0.63985672 0.21177129 0.52830069]
   [0.66856852 0.5387767  0.70876114]]

  ...

  [[0.51489322 0.08210204 0.91840577]
   [0.42494644 0.39048398 0.42675387]
   [0.03565494 0.19802553 0.13046423]
   ...
   [0.91238706 0.46521815 0.1786866 ]
   [0.71185371 0.53977706 0.63746035]
   [0.3992324  0.01743369 0.52732087]]

  [[0.83117598 0.93069215 0.2936553 ]
   [0.7

---
#### <span style="color:chocolate">Exercise 5: </span>Mathematical operations on numpy arrays (15 points)

Create a (3, 2) numpy array (you can name it my_array4) containing only integer values. Perform the following tasks:

1. Print the shape of the array;
2. Print the sum of all elements (hint: the axis argument is set to None);
3. Print the sum of all elements by column;
3. Print the sum of all elements by row and change the type of the resulting array elements to float;
5. Print the first row of the array;
6. Print the second row of the array;
7. Select the element at position (1, 0);
8. Modify the element at position (2, 1) by setting its value to 10 and print the array again;
9. Loop over elements in the array. Print the output.

In [14]:
# YOUR CODE HERE
my_array4 = np.array([[1, 2], [3, 4], [5, 6]])

# Print the shape of the array
print("Shape of the array:", my_array4.shape)

# Print the sum of all elements (hint: the axis argument is set to None)
total_sum = np.sum(my_array4, axis=None)
print("Sum of all elements:", total_sum)

# Print the sum of all elements by column
sum_by_column = np.sum(my_array4, axis=0)
print("Sum by column:", sum_by_column)

# Print the sum of all elements by row and change the type of the resulting array elements to float
sum_by_row = np.sum(my_array4, axis=1).astype(float)
print("Sum by row (as float):", sum_by_row)

# Print the first row of the array
print("First row of the array:", my_array4[0])

# Print the second row of the array
print("Second row of the array:", my_array4[1])

# Select the element at position (1, 0)
element_at_1_0 = my_array4[1, 0]
print("Element at position (1, 0):", element_at_1_0)

# Modify the element at position (2, 1) by setting its value to 10 and print the array again
my_array4[2, 1] = 10
print("Array after modifying element at position (2, 1):")
print(my_array4)

# Loop over elements in the array. Print the output
print("Loop over elements in the array:")
for a in my_array4.flat:  # .flat allows iteration over all elements
    print(a)

Shape of the array: (3, 2)
Sum of all elements: 21
Sum by column: [ 9 12]
Sum by row (as float): [ 3.  7. 11.]
First row of the array: [1 2]
Second row of the array: [3 4]
Element at position (1, 0): 3
Array after modifying element at position (2, 1):
[[ 1  2]
 [ 3  4]
 [ 5 10]]
Loop over elements in the array:
1
2
3
4
5
10


You can find more examples here: https://numpy.org/doc/stable/reference/routines.math.html

---
#### <span style="color:chocolate">Exercise 6:</span> Create arrays (15 points)

1. Create and print a (3,2) numpy array of pixel values between 0 and 1.
2. Create and print a (27,) numpy array representing years from 1991 to 2017
3. Create and print a (3, 5, 10) numpy array of zeros
4. Create and print a (3, 5, 10) numpy array of ones
5. Create and print an array with a constant value (let's say 5) using np.ones()
6. Create and print an array with random numbers drawn from a normal distribution with mean 0 and standard deviation 1. Set the sample size to 10.


In [7]:
# YOUR CODE HERE
# Create and print a (3,2) numpy array of pixel values between 0 and 1.
array_1 = np.random.random((3, 2))
print(array_1)

# Create and print a (27,) numpy array representing years from 1991 to 2017
array_2 = np.arange(1991, 2018)
print(array_2)

# Create and print a (3, 5, 10) numpy array of zeros
array_3 = np.zeros((3, 5, 10))
print(array_3)

# Create and print a (3, 5, 10) numpy array of ones
array_4 = np.ones((3, 5, 10))
print(array_4)

# Create and print an array with a constant value (let's say 5) using np.ones()
array_5 = np.ones((3, 5, 10)) * 5
print(array_5)

# Create and print an array with random numbers drawn from a normal distribution with mean 0 and standard deviation 1. Set the sample size to 10.
array_6 = np.random.normal(0, 1, 10)
print(array_6)

[[0.66869277 0.86371304]
 [0.10115908 0.70845544]
 [0.52986759 0.85683632]]
[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 

---
#### <span style="color:chocolate">Exercise 7:</span> Reshape arrays (10 points)

Consider the following array:

In [17]:
years = np.arange(1991, 2018, 1)
print(years)
print(years.shape)

[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
(27,)


Perform the following operations on this array:
    
1. Create 3 nested arrays, each of size (3, 3). Call this array years_3d;
2. Convert the years_3d array to a flat 1D array. Call this array years_1d;
3. Add a new axis (in front) to the years_1d array. Call this array years_2d;
4. Remove the first axis from years_2d array. Call this array years_1d.

For each exercise print the array and its shape.

In [21]:
# YOUR CODE HERE
# Create 3 nested arrays, each of size (3, 3). Call this array years_3d
print(years)

years_3d = years.reshape(3, 3, 3)
print(years_3d)
print("Shape:", years_3d.shape)

# Convert the years_3d array to a flat 1D array. Call this array years_1d
years_1d = years_3d.flatten()
print("Shape:", years_1d.shape)

# Add a new axis (in front) to the years_1d array. Call this array years_2d
years_2d = years_1d[np.newaxis, :]
print(years_2d)
print("Shape:", years_2d.shape)

# Remove the first axis from years_2d array. Call this array years_1d
years_1d_again = np.squeeze(years_2d, axis=0)
print(years_1d_again)
print("Shape:", years_1d_again.shape)

[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
[[[1991 1992 1993]
  [1994 1995 1996]
  [1997 1998 1999]]

 [[2000 2001 2002]
  [2003 2004 2005]
  [2006 2007 2008]]

 [[2009 2010 2011]
  [2012 2013 2014]
  [2015 2016 2017]]]
Shape: (3, 3, 3)
Shape: (27,)
[[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
  2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]]
Shape: (1, 27)
[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
Shape: (27,)


---
#### <span style="color:chocolate">Exercise 8:</span> Joining arrays (10 points)

Provide 8 examples that use the methods <span style="color:cornflowerBlue">np.concatenate()</span> and <span style="color:cornflowerBlue">np.stack()</span>. Note: create 4 examples using each method.

In [26]:
# YOUR CODE HERE
# np.concatenate(): Joins arrays along an existing axis.
# np.stack(): Joins arrays along a new axis, creating an additional dimension.

# Concatenating 1D Arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

result = np.concatenate((array1, array2))
print(result)

# Concatenating 2D Arrays Along Axis 0 (Rows)
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

result = np.concatenate((array1, array2), axis=0)
print(result)

# Concatenating 2D Arrays Along Axis 1 (Columns)
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

result = np.concatenate((array1, array2), axis=1)
print(result)

# Concatenating 3D Arrays Along a New Axis
array1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array2 = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])

result = np.concatenate((array1, array2), axis=0)
print(result)

# Stacking 1D Arrays Along a New Axis
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print("stack 1d")
result = np.stack((array1, array2), axis=0)
print(result)

# Stacking 2D Arrays Along a New Axis (Depth)
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

result = np.stack((array1, array2), axis=2)
print(result)

# Stacking 3D Arrays Along a New Axis (Creating a 4D Array)
array1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array2 = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])

result = np.stack((array1, array2), axis=0)
print(result)

# Stacking Multiple 1D Arrays Along Axis 1 (Creating a 2D Array)
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.array([7, 8, 9])

result = np.stack((array1, array2, array3), axis=1)
print(result)


[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
stack 1d
[[1 2 3]
 [4 5 6]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


---
#### <span style="color:chocolate">Numpy broadcasting</span> 

The term broadcasting describes how NumPy treats arrays during arithmetic operations. You can find more here:  https://numpy.org/doc/stable/user/basics.broadcasting.html

In [13]:
# multiplying an array with a scalar
years = np.arange(1991, 2018, 1)
years * 1

array([1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017])

In [14]:
# adding a scalar
years + 2

array([1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019])

In [15]:
# many arithmetic operations are applied element wise on a pair of arrays
a = np.arange(3)
print('Array a:', a)
b = np.arange(3)
print('Array b:', b)
print('Sum of a and b:', a+b)

Array a: [0 1 2]
Array b: [0 1 2]
Sum of a and b: [0 2 4]


In [16]:
# another example
a = np.ones((3, 3))
print('Array a:', a)
b = np.arange(3)
print('\nArray b:', b)
print('\nSum of a and b:', a+b)

Array a: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array b: [0 1 2]

Sum of a and b: [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


---
#### <span style="color:chocolate">Exercise 9:</span> Numpy array standardization (10 points)

Consider the following (10, 4) array:

In [17]:
my_array = np.random.random((10, 4))
print('my_array shape: ', my_array.shape)
my_array

my_array shape:  (10, 4)


array([[9.89537574e-01, 9.44649530e-01, 2.59047822e-02, 2.41036029e-01],
       [2.09232762e-01, 6.91936843e-01, 7.02465192e-01, 5.92360703e-01],
       [2.85496978e-01, 9.10061264e-02, 4.74607622e-01, 2.44213847e-01],
       [3.08055169e-02, 6.55060658e-01, 9.80750478e-04, 4.46020788e-01],
       [9.63664756e-01, 3.86439740e-01, 4.09421652e-01, 2.32061314e-02],
       [3.67139198e-02, 3.02058733e-01, 9.58056443e-01, 7.91801052e-01],
       [5.15142500e-01, 9.26690622e-02, 6.01623233e-01, 4.45338123e-01],
       [8.85537478e-01, 7.66971472e-01, 4.99193674e-01, 5.89632232e-02],
       [5.72399954e-01, 2.03701092e-01, 4.48716641e-01, 3.28975282e-01],
       [4.14938107e-01, 6.23857395e-01, 1.23721126e-01, 8.80021615e-01]])

Peform the following operations on this array:
1. Compute and print the mean and std for each column (note: set keepdims=True for proper broadcasting).
2. Standardize and print the array and its shape using the mean and std you computed above.

In [18]:
# YOUR CODE HERE
# Compute and print the mean and std for each column (note: set keepdims=True for proper broadcasting).
mean = np.mean(my_array, axis=0, keepdims=True)
std = np.std(my_array, axis=0, keepdims=True)
print("\nMean for each column:")
print(mean)
print("Standard deviation for each column:")
print(std)

# Standardize and print the array and its shape using the mean and std you computed above.
standardized_array = (my_array - mean) / std
print("\nStandardized array:")
print(standardized_array)
print("Shape of the standardized array:", standardized_array.shape)


Mean for each column:
[[0.49034695 0.47583507 0.42446911 0.40519368]]
Standard deviation for each column:
[[0.34356667 0.28503262 0.28825997 0.27160601]]

Standardized array:
[[ 1.45296581  1.64477478 -1.38265583 -0.60439623]
 [-0.81822313  0.75816507  0.96439363  0.68911223]
 [-0.5962452  -1.35012245  0.17393504 -0.59269613]
 [-1.33756119  0.62878976 -1.46911956  0.1503174 ]
 [ 1.37765927 -0.31363191 -0.052201   -1.40640314]
 [-1.32036393 -0.60967173  1.85106288  1.42341243]
 [ 0.07217099 -1.34428825  0.61456372  0.14780396]
 [ 1.15025863  1.02141434  0.25922629 -1.27475255]
 [ 0.23882701 -0.95474677  0.08411688 -0.28062117]
 [-0.21948825  0.51931716 -1.04332206  1.74822322]]
Shape of the standardized array: (10, 4)


----
#### <span style="color:chocolate">Additional practice question</span> (not graded)

Consider the following image:

In [5]:
my_image = np.arange(0, 1, 0.04).reshape(5,5)
print(my_image)
my_image.shape

[[0.   0.04 0.08 0.12 0.16]
 [0.2  0.24 0.28 0.32 0.36]
 [0.4  0.44 0.48 0.52 0.56]
 [0.6  0.64 0.68 0.72 0.76]
 [0.8  0.84 0.88 0.92 0.96]]


(5, 5)

Perform the following operations on this image (do not overwrite the original image):

1. Crop by using a border of size 1;
2. Crop by removing:
    * the first and the last two rows, and
    * the first and the last two columns;
3. Reverse the column order;
4. set to 0.5 elements divizible by 2.

In [20]:
# YOUR CODE HERE
# Task 1: Crop by using a border of size 1
cropped_image_1 = my_image[1:-1, 1:-1]
print("\nCropped image (border of size 1):")
print(cropped_image_1)

# Task 2: Crop by removing the first and last two rows and columns
cropped_image_2 = my_image[2:-2, 2:-2]
print("\nCropped image (remove first and last two rows and columns):")
print(cropped_image_2)

# Task 3: Reverse the column order
reversed_columns_image = my_image[:, ::-1]
print("\nImage with reversed column order:")
print(reversed_columns_image)

# Task 4: Set to 0.5 elements divisible by 2
modified_image = np.copy(my_image)  # Make a copy to avoid modifying the original
modified_image[modified_image % 2 == 0] = 0.5
print("\nImage with elements divisible by 2 set to 0.5:")
print(modified_image)


Cropped image (border of size 1):
[[0.24 0.28 0.32]
 [0.44 0.48 0.52]
 [0.64 0.68 0.72]]

Cropped image (remove first and last two rows and columns):
[[0.48]]

Image with reversed column order:
[[0.16 0.12 0.08 0.04 0.  ]
 [0.36 0.32 0.28 0.24 0.2 ]
 [0.56 0.52 0.48 0.44 0.4 ]
 [0.76 0.72 0.68 0.64 0.6 ]
 [0.96 0.92 0.88 0.84 0.8 ]]

Image with elements divisible by 2 set to 0.5:
[[0.5  0.04 0.08 0.12 0.16]
 [0.2  0.24 0.28 0.32 0.36]
 [0.4  0.44 0.48 0.52 0.56]
 [0.6  0.64 0.68 0.72 0.76]
 [0.8  0.84 0.88 0.92 0.96]]
